openapi: 3.0.0
info:
  title: CesiZen
  version: 1.0.0
  description: API pour CesiZen
servers:
  - url: http://localhost:8081
    description: Local server
paths:
  #

  /api/user:
    $ref: './user/user.yaml'

  /api/user/{id}:
    $ref: './user/userById.yaml'

  /api/login:
    $ref: './login/login.yaml'

  /api/register:
    $ref: './register/register.yaml'