openapi: 3.0.0
info:
  title: CesiZen
  version: 1.0.0
  description: API pour CesiZen
servers:
  - url: http://localhost:8081
    description: Local server
paths:
  #

  /api/user:
    $ref: './user/user.yaml'

  /api/user/{id}:
    $ref: './user/userById.yaml'


  /api/login:
    $ref: './login/login.yaml'


  /api/register:
    $ref: './register/register.yaml'



  /api/ressource:
    $ref: './ressource/ressource.yaml'

  /api/ressource/{id}:
    $ref: './ressource/updateRessource.yaml'

  /api/ressource{id}:
    $ref: './ressource/deleteRessource.yaml'



  /api/respiration:
    $ref: './respiration/respiration.yaml'

  /api/respiration/{id}:
    $ref: './respiration/updateRespiration.yaml'

  /api/respiration{id}:
    $ref: './respiration/deleteRespiration.yaml'



  /api/meditation:
    $ref: './meditation/meditation.yaml'

  /api/meditation/{id}:
    $ref: './meditation/updateMeditation.yaml'

  /api/meditation{id}:
    $ref: './meditation/deleteMeditation.yaml'